#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CircularProgressButton.Resource", IsApplication=true)]

namespace CircularProgressButton
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int sample_list = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010008
			public const int cpb_colorIndicator = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int cpb_colorIndicatorBackground = 2130771977;
			
			// aapt resource value: 0x7f010007
			public const int cpb_colorProgress = 2130771975;
			
			// aapt resource value: 0x7f01000c
			public const int cpb_cornerRadius = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int cpb_iconComplete = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int cpb_iconError = 2130771978;
			
			// aapt resource value: 0x7f01000d
			public const int cpb_paddingProgress = 2130771981;
			
			// aapt resource value: 0x7f010001
			public const int cpb_selectorComplete = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cpb_selectorError = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int cpb_selectorIdle = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int cpb_textComplete = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cpb_textError = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cpb_textIdle = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int cpb_textProgress = 2130771974;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int cpb_blue = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int cpb_blue_dark = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int cpb_complete_state_selector = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int cpb_error_state_selector = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int cpb_green = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int cpb_green_dark = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int cpb_grey = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int cpb_idle_state_selector = 2130968586;
			
			// aapt resource value: 0x7f040005
			public const int cpb_red = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int cpb_red_dark = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int cpb_white = 2130968583;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int cpb_stroke_width = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int complete_state_selector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cpb_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int error_state_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_accept = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_cancel = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_launcher = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int idle_state_selector = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int circularButton1 = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int circularButton2 = 2131296257;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ac_sample_1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ac_sample_2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ac_sample_3 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ac_sample_4 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ac_sample_5 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int layout1 = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06000d
			public const int Complete = 2131099661;
			
			// aapt resource value: 0x7f060012
			public const int CustomSelectorSample = 2131099666;
			
			// aapt resource value: 0x7f06000c
			public const int Error = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int IndeterminateProgressSample = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int IntegerProgressSample = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int ProgressPaddingSample = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int StateChangeSample = 2131099664;
			
			// aapt resource value: 0x7f06000b
			public const int Upload = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int app_name = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int define_circularprogressbutton = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int library_circularprogressbutton_author = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int library_circularprogressbutton_authorWebsite = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int library_circularprogressbutton_isOpenSource = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int library_circularprogressbutton_libraryDescription = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int library_circularprogressbutton_libraryName = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int library_circularprogressbutton_libraryVersion = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int library_circularprogressbutton_libraryWebsite = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int library_circularprogressbutton_licenseId = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int library_circularprogressbutton_repositoryLink = 2131099657;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int AppTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircularProgressButton = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 8
			public const int CircularProgressButton_cpb_colorIndicator = 8;
			
			// aapt resource value: 9
			public const int CircularProgressButton_cpb_colorIndicatorBackground = 9;
			
			// aapt resource value: 7
			public const int CircularProgressButton_cpb_colorProgress = 7;
			
			// aapt resource value: 12
			public const int CircularProgressButton_cpb_cornerRadius = 12;
			
			// aapt resource value: 11
			public const int CircularProgressButton_cpb_iconComplete = 11;
			
			// aapt resource value: 10
			public const int CircularProgressButton_cpb_iconError = 10;
			
			// aapt resource value: 13
			public const int CircularProgressButton_cpb_paddingProgress = 13;
			
			// aapt resource value: 1
			public const int CircularProgressButton_cpb_selectorComplete = 1;
			
			// aapt resource value: 2
			public const int CircularProgressButton_cpb_selectorError = 2;
			
			// aapt resource value: 0
			public const int CircularProgressButton_cpb_selectorIdle = 0;
			
			// aapt resource value: 3
			public const int CircularProgressButton_cpb_textComplete = 3;
			
			// aapt resource value: 5
			public const int CircularProgressButton_cpb_textError = 5;
			
			// aapt resource value: 4
			public const int CircularProgressButton_cpb_textIdle = 4;
			
			// aapt resource value: 6
			public const int CircularProgressButton_cpb_textProgress = 6;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
